### ISSUE TITLE
SgminerFancyIX returned invalid object

### ISSUE THREAD

**Issue by farrarj86** [RainbowMiner/RainbowMiner#1590] opened 2021-05-12 22:43 UTC
I just got up and running on a fresh Win10 install after having issues getting my Radeon RX 5500 XT discovered on Fedora 34. I not get this warning with every run. 

`WARNING: Miner module SgminerFancyIX returned invalid object. Please open an issue at https://github.com/rainbowminer/RainbowMiner/issues`

**Comment by RainbowMiner** [comment] 2021-05-13 08:37
Thank you for reporting this. I'll look into it (duplicate of issue #1581)

**Closed** 2021-07-09 11:11 UTC
Labels: duplicate, miner issue, solved
