### ISSUE TITLE
Dowload in progress... stuck

### ISSUE THREAD

**Issue by Djago** [RainbowMiner/RainbowMiner#464] opened 2019-03-11 04:04 UTC
Hi!
I made a trip and when I get back to work I've fired up RM (I think it was 3.9.8.5?) and after the update to 3.9.9.3 RM is stuck at "WARNING: Download in progress: 7 miners left. Command windows will popup during extraction."
I've tried restarting the miner to no avail.

**Comment by Djago** [comment] 2019-03-11 05:21
I've restarted the PC twice and now it started downloading again...

**Comment by RainbowMiner** [comment] 2019-03-11 22:03
It has been most likely been caused by ttminer - it makes use of JRE. Better uninstall JRE

**Comment by Djago** [comment] 2019-03-11 22:46
I'm still having issues in 3.9.9.5. I still have 1 miner left that won't donwload. I don't have JRE installed

**Comment by RainbowMiner** [comment] 2019-03-12 09:55
Ok, let's see, which miner got stuck:
http://localhost:4000/downloadlist
.. what does it say?

**Comment by Djago** [comment] 2019-03-12 15:10
> [
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.3.6-cpuminermulti/cpuminer-multi-1.3.6.7z",
    "Path": "D:\\CryptoCurrencies\\RainbowMiner\\Bin\\CPU-Multi\\cpuminer-avx2-sha.exe",
    "Searchable": true,
    "IsMiner": true
  }
]

Still downloading...

**Comment by Djago** [comment] 2019-03-12 15:48
I got:

> Cannot find path 'D:\CryptoCurrencies\RainbowMiner\Bin\CPU-Multi' because it does not exist.
+ CategoryInfo          : ObjectNotFound: (D:\CryptoCurren...r\Bin\CPU-Multi:String) [Copy-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
+ PSComputerName        : localhost

**Comment by RainbowMiner** [comment] 2019-03-12 16:15
Ah! Ok, now I can imagine the problem. I will provide a fixed miner file for this one.

**Comment by RainbowMiner** [comment] 2019-03-12 16:35
Na, that's weird. It should download. Could you please try to stop RainbowMiner, then delete all ".\Bin\CPU-Multi" folders and then try to restart RBM?
Did this work?

**Comment by RainbowMiner** [comment] 2019-03-12 16:43
If this does not work, just delete the file .\Miners\CpuminerMulti.ps1 - it is a collection of all the tpruvot cpu miners. Actually, looking at it, maybe we could remove it. I don't see it's faster than the others.

**Comment by Djago** [comment] 2019-03-13 03:52
3.9.9.6 solved the issue after the update. If it happens again I'll report it here

**Comment by Djago** [comment] 2019-03-13 12:05
3.9.9.7 smoothly downloaded all miners

**Comment by Djago** [comment] 2019-03-15 02:18
3.9.9.8 downloaded all miners OK

**Comment by Djago** [comment] 2019-06-04 05:41
I'm having this issue again. I have one stuck download since Saturday and 4 updates have passed by since then.
http://localhost:4000/downloadlist gives me:
[
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v3.9.1.1-jayddee/cpuminer-opt-jayddee-3.9.1.1-win.zip",
    "Path": "D:\\CryptoCurrencies\\RainbowMiner\\Bin\\CPU-JayDDee\\cpuminer-avx2-sha.exe",
    "Searchable": true,
    "IsMiner": true
  }
]

What should I do?

**Comment by RainbowMiner** [comment] 2019-06-04 07:14
Oh! Eventually Jayddee did remove one of the CPU optimized executables. I will check and release a fixed version, asap.

**Comment by RainbowMiner** [comment] 2019-06-04 07:29
Your rig runs on a Ryzen, doesn't it?

**Comment by RainbowMiner** [comment] 2019-06-04 08:22
It should be fixed, now. I will push a release, soon.

**Comment by Djago** [comment] 2019-06-04 11:44
> Your rig runs on a Ryzen, doesn't it?

Yes

**Comment by BrettMontague** [comment] 2019-07-12 14:11
I'm having a similar problem with a couple of miners:

On Intel / Nvidia, Ubuntu 18.04.

Here is the localhost:4000/downloadlist output:

  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v12.0-claymoredual/ClaymoreDual-12.0.tar.gz",
    "Path": "/home/xxxxx/RainbowMiner/Bin/Ethash-Claymore/ethdcrminer64",
    "Searchable": true,
    "IsMiner": true
  },
  {
    "URI": "https://github.com/RainbowMiner/miner-binaries/releases/download/v1.1.23-ccminermtp/ccminermtp-v1.1.23-linux.7z",
    "Path": "/home/xxxxx/RainbowMiner/Bin/NVIDIA-CcminerMTP/ccminer-linux-cuda101",
    "Searchable": true,
    "IsMiner": true
  }
]

It also seems like it's stuck on benchmarking this:

Miner          Algorithms Aprox. Time
-----          ---------- -----------
ClaymoreEthash Ethash     2-4 minutes

for the past 12 hours or so.

**Comment by RainbowMiner** [comment] 2019-07-12 20:03
Oh!! Thank you very much for bringing this up! There is indeed a bug in the linux ClaymoreDual module. I'll fix it asap.

**Comment by RainbowMiner** [comment] 2019-07-12 20:14
Good, I fixed it. Just update to the newest release V4.3.5.2 and everything should be fine.

**Closed** 2020-01-11 10:42 UTC
Labels: miner issue
