### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by samdave123** [RainbowMiner/RainbowMiner#755] opened 2019-12-08 14:11 UTC
![image](https://user-images.githubusercontent.com/56473344/70390636-9e662480-19c4-11ea-8539-5f31b57b42c8.png)

![image](https://user-images.githubusercontent.com/56473344/70390638-a45c0580-19c4-11ea-8fbe-50d0e783bb49.png)

**Comment by RainbowMiner** [comment] 2019-12-08 17:26
Oh no! Which version of RainbowMiner are you using? Could you please create a Debug file and upload it?

**Comment by samdave123** [comment] 2019-12-08 17:27
4.4.8.2

**Comment by samdave123** [comment] 2019-12-08 17:27
[debug_2019-12-08.zip](https://github.com/RainbowMiner/RainbowMiner/files/3936621/debug_2019-12-08.zip)

**Comment by RainbowMiner** [comment] 2019-12-08 17:35
Oh, I see, please update to the current version. I have finally discovered one memory leak (related to MRR) and got it fixed since 4.4.8.3

**Comment by RainbowMiner** [comment] 2019-12-08 18:12
There is something very odd about the log files on your system. Is your disk full? If not, please do a restart of the machine, it may be the case, that windows blocks some files.

**Comment by samdave123** [comment] 2019-12-08 18:13
Disk is not full. I don't see anything wrong with the log files? What is odd about them?

**Comment by RainbowMiner** [comment] 2019-12-08 19:14
There is one file empty, which should contain the whole transcript:
RainbowMiner_2019-12-08_14-15-25.txt

.. ah, another question: did you have your web browser pointing to a specific localhost page? The memory usage has been increasing quite fast, so I really want to get to the bottom of it.

**Comment by samdave123** [comment] 2019-12-08 20:12
I switch between localhost pages, although I have it on the Dashboard more than any other.

**Comment by RainbowMiner** [comment] 2019-12-08 22:33
Thank you. I'll investigate closer. You could help a great deal, if you could create me a full memory dump.
Download https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer from Microsoft, extract to some folder and start `procexp64.exe` with admin rights. Now find the pwsh.exe:
![image](https://user-images.githubusercontent.com/39437538/70397461-ad73c380-1a12-11ea-8f19-68c6268cd79b.png)

.. right-click on it, go to "Create Dump" and then click "Create full dump.."

It will create a rather big file, so zip it and then upload it here. If it is too large for an upload, please let me know. With this file, I can easily find out, which culprit causes that memory leak.

**Comment by samdave123** [comment] 2019-12-10 17:57
Still seems to be an issue 

![image](https://user-images.githubusercontent.com/56473344/70555183-75859100-1b76-11ea-84e3-66438ded2835.png)

![image](https://user-images.githubusercontent.com/56473344/70555194-79191800-1b76-11ea-9d31-0324a7f368a9.png)

**Comment by samdave123** [comment] 2019-12-10 18:06
The dump is too large, can you get on Discord and let me send it there?

**Comment by RainbowMiner** [comment] 2019-12-13 10:05
I have been able to reproduce this. It seems to be some imbalance between memory garbage collection and some synchronized hash tables. It happens only, if you leave a localhost open in your browser. I will remove this problem (hopefully) pretty soon.

**Comment by samdave123** [comment] 2019-12-13 10:09
Ah that makes sense, I do tend to leave my localhost open most of the time as I prefer to interact with RBM that way rather than remoting into the rig. Thanks for your efforts on this.

**Comment by samdave123** [comment] 2019-12-23 20:18
Looks like it still exists?

![image](https://user-images.githubusercontent.com/56473344/71378930-6a445380-25c1-11ea-8e20-b648a6f20663.png)

**Comment by RainbowMiner** [comment] 2019-12-23 22:33
Yes - I am already investigating since some days, now. It is a pretty tough nut.

**Comment by RainbowMiner** [comment] 2019-12-27 11:02
This leak did cost me some sleepless nights, but it is finally resolved in v4.4.9.9

**Closed** 2020-01-11 10:37 UTC
Labels: bug, solved
