### ISSUE TITLE
Reject share feature

### ISSUE THREAD

**Issue by hernandn01** [RainbowMiner/RainbowMiner#437] opened 2019-02-20 13:20 UTC
How long does it take for the miner to be considered not working?
![image](https://user-images.githubusercontent.com/41829368/53094519-8fff5880-34d7-11e9-8fb8-54b48955c42a.png)

**Comment by ebojali** [comment] 2019-02-20 13:44
Accordin to the release it should be set to 30% but same here.. Did not happen.

**Comment by hernandn01** [comment] 2019-02-20 13:46
mine was 100% reject, maybe there is no point of comparison starting from zero.

**Comment by RainbowMiner** [comment] 2019-02-21 13:58
The rejected shares will not be checked during benchmark. But it looks like the TTminer does not report correctly. I will have a look.

**Comment by hernandn01** [comment] 2019-02-21 14:08
to clarify, it was not benchmarking. It was during yesterday's issue with MTP and Nicehash

**Comment by RainbowMiner** [comment] 2019-02-21 15:13
Yes, I see. I am currently investigating this issue.

**Comment by RainbowMiner** [comment] 2019-02-21 15:49
Oh dear! That was an evil one. I found the cause and fixed it. Will be in next release v3.9.7.6

**Comment by hernandn01** [comment] 2019-02-21 15:49
thanks

**Closed** 2019-02-22 19:55 UTC
Labels: bug, miner issue, solved
