### ISSUE TITLE
RainbowMiner keeps changing my RTM mining address

### ISSUE THREAD

**Issue by papadrams** [RainbowMiner/RainbowMiner#2070] opened 2022-05-18 11:56 UTC
Hallo again,
For the last week or so, i have this problem. I set up my RTM address and couple of hours later, rainbowminer changes it to somewhat else. An address i have never used and doesnt belong to me. I have tried to change it through the miner itself and its menus, worked for a little bit but reverted back to this uknown address. i tried to set the rtm address per pool but rainbowminer changed that as well.
Yesterday or 2 days ago i deleted everything and set it up again from scratch. The RTM address changed again to that same address as before. Which i do not own.... I attach the debug file. Please help sort this out
[debug_2022-05-18.zip](https://github.com/RainbowMiner/RainbowMiner/files/8715946/debug_2022-05-18.zip)
.

**Comment by papadrams** [comment] 2022-05-18 13:45
It changes the address in the config files as well

**Comment by RainbowMiner** [comment] 2022-05-18 13:51
That would mean, that somebody has access to your PC, either directly or via the localhost API. Please do the following: 
- setup a username and password for your API
- lock the API config and unlock it only, when you plan to make some changes via the http://localhost:4000 API

In config.txt:
```
  "APIlockConfig": "1",
  "APIauth": "1",
  "APIuser": "someusername",
  "APIpassword": "somepassword",
```

**Comment by RainbowMiner** [comment] 2022-05-18 13:56
Also, in case this happens again - please write down the unknown RTM address and share it here. I would like to do some reverse lookup.

**Comment by papadrams** [comment] 2022-05-18 14:00
I have it already. 
R9vHLDZPhpt8nynX3iRVDXPj3YRqN7vpsB

**Comment by jch9678** [comment] 2022-05-18 16:31
I wonder if that's the same address that mine was changing to.  @papadrams Which coin is that for?  Did your btc or eth address change?

@RainbowMiner 
If it's someone that has access to API, how is that person finding an ip address that uses RM, and then has the knowledge to change the config files?

If it's someone that has remote capability, then how did that person gain that capability and have somewhat of knowledge how RM functions?

This experiment will be interesting.  Well maybe, if the attacker has knowledge about RM, they are probably monitoring Github Issues.

**Comment by jch9678** [comment] 2022-05-19 19:50
With this commit, you're thinking an attacker could be perusing debug files and finding ip addresses that way?  I should point out that I've never used the default 4000 as the API port.

**Comment by RainbowMiner** [comment] 2022-05-19 20:13
> With this commit, you're thinking an attacker could be perusing debug files and finding ip addresses that way? I should point out that I've never used the default 4000 as the API port.

It's just a maybe. There might in fact be some log files that contain IP addresses. With that last commit, I can be 100% sure, that all IP addresses will be x-ed out in the Debug file.

**Comment by papadrams** [comment] 2022-05-20 09:34
> I wonder if that's the same address that mine was changing to. @papadrams Which coin is that for? Did your btc or eth address change?
> 
> @RainbowMiner If it's someone that has access to API, how is that person finding an ip address that uses RM, and then has the knowledge to change the config files?
> 
> If it's someone that has remote capability, then how did that person gain that capability and have somewhat of knowledge how RM functions?
> 
> This experiment will be interesting. Well maybe, if the attacker has knowledge about RM, they are probably monitoring Github Issues.

Its for raptoreum. I am currently mining on zpool and gettin paid in rtm. So i have no idea about BTC or ETH.

**Comment by papadrams** [comment] 2022-05-20 09:34
So 48 hours passed and since i have locked the config files no change has been detected. it looks like it worked. Thanks for the help.

**Comment by RainbowMiner** [comment] 2022-05-20 09:40
@papadrams Thank you for the feedback! I will improve the setup process, so that new users will be strongly encouraged to use API username and password.

**Closed** 2022-05-20 09:42 UTC

**Comment by jch9678** [comment] 2022-05-20 16:24
@papadrams keep an eye on it,  Just because you weren't attacked in 48 hours doesn't necessarily mean the problem is fixed.  It just means you weren't attacked in 48 hours.  But hopefully it does work.
